%define module	sphinxcontrib-googleanalytics

Summary:	Sphinx extension for Google Analytics HTML files
Name:		python-%{module}
Version:	0.1
Release:	1
Source0:	https://files.pythonhosted.org/packages/source/s/%{module}/%{module}-%{version}.tar.gz
License:	BSD
Group:		Development/Python
Url:		https://pypi.org/project/sphinxcontrib-googleanalytics/
BuildArch:	noarch
Requires:	python-sphinx >= 0.6
BuildRequires:	python-setuptools

%description
This Sphinx extension tracks HTML files generated by the Google
Analytics web service.

%prep
%setup -q -n %{module}-%{version}

%install
%__rm -rf %{buildroot}
PYTHONDONTWRITEBYTECODE= %__python setup.py install --root=%{buildroot}

%files
%defattr(-,root,root)
%doc README
%py_sitedir/sphinxcontrib*
