%define module sphinxcontrib-googleanalytics
%define oname sphinxcontrib_googleanalytics

Name:		python-sphinxcontrib-googleanalytics
Summary:	Sphinx extension for Google Analytics
Version:	0.5
Release:	1
License:	BSD-3-Clause
Group:		Development/Python
URL:		https://github.com/sphinx-contrib/googleanalytics
Source0:	https://github.com/sphinx-contrib/googleanalytics/archive/v%{version}/%{name}-%{version}.tar.gz

BuildSystem:	python
BuildArch:	noarch
BuildRequires:	python%{pyver}dist(pip)
BuildRequires:	python%{pyver}dist(setuptools)
BuildRequires:	python%{pyver}dist(wheel)

%description
This Sphinx extension tracks HTML files generated by the Google
Analytics web service.

%prep -a
# Fix shebangs
sed -i 's:^#!/usr/bin/env python:#!%{__python}:' \
	sphinxcontrib/googleanalytics.py

%install -a
# Set executable bit on installed python scripts
chmod +x %{buildroot}%{python_sitelib}/sphinxcontrib/googleanalytics.py

%files
%doc README.rst
%{python_sitelib}/sphinxcontrib
%{python_sitelib}/%{oname}-%{version}.dist-info

