%define module	sphinxcontrib-googleanalytics
%define name	python-%{module}
%define version	0.1
%define	rel		1
%if %mdkversion < 201100
%define release %mkrel %{rel}
%else
%define	release	%{rel}
%endif

Summary:	Sphinx extension for Google Analytics HTML files
Name:		%{name}
Version:	%{version}
Release:	%{release}
Source0:	http://pypi.python.org/packages/source/s/%{module}/%{module}-%{version}.tar.gz
License:	BSD
Group:		Development/Python
Url:		http://pypi.python.org/pypi/sphinxcontrib-googleanalytics/
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-buildroot
BuildArch:	noarch
Requires:	python-sphinx >= 0.6
BuildRequires:	python-setuptools

%description
This Sphinx extension tracks HTML files generated by the Google
Analytics web service.

%prep
%setup -q -n %{module}-%{version}

%install
%__rm -rf %{buildroot}
PYTHONDONTWRITEBYTECODE= %__python setup.py install --root=%{buildroot}

%clean
%__rm -rf %{buildroot}

%files
%defattr(-,root,root)
%doc README
%py_sitedir/sphinxcontrib*


%changelog
* Tue Jul 10 2012 Lev Givon <lev@mandriva.org> 0.1-1
+ Revision: 808758
- imported package python-sphinxcontrib-googleanalytics

